#!/usr/bin/env bash

host=${HOST:-neuropurkki}
prefix=${MODEL:-model}
model_name="${prefix}-$(date +"%Y%m%dT%H%M%S")"
mdir="~/c2w2c/MODELS/$model_name"
remote_cmd="source ~/.bash_profile && cd $mdir && $@"

ssh -t ${host} "mkdir -p $mdir/data && mkdir -p $mdir/src "
echo "#!/usr/bin/env bash
$remote_cmd
" > run_model.sh && chmod 755 run_model.sh
scp -r data/* ${host}:${mdir}/data/
scp -r src/* ${host}:${mdir}/src/
scp run_model.sh run ${host}:${mdir}
rm run_model.sh

ssh -t ${host} "screen -UmS $model_name bash -c \"$mdir/run_model.sh\""
