#!/usr/bin/env bash

if [ "$1" == "" ]; then
  echo "Usage: ./run <keras-script>"
  exit 1
fi

# Xcode 7 is not working with Theano at the moment
if [ "x$OSX" == "x1" ]; then
  echo "OS X flag detected, using Xcode 6.4"
  export DEVELOPER_DIR=/Applications/Xcode_6.4.app/Contents/Developer
fi

device=${DEVICE:-gpu}

if [ "x$MODE" == "xdev" ]; then
  flags=mode=FAST_COMPILE,device=cpu,floatX=float32,optimizer=None,exception_verbosity=high
else
  flags=mode=FAST_RUN,device=$device,floatX=float32
fi

find ./src -name "*.pyc" -exec rm -rf {} \;

THEANO_FLAGS=$flags python -m src $@
